package jcf;

/**
 * Auto-generated by JettraAppServer from jettra-config.properties.
 */
public enum AppRole {
    ADMIN,
    MANAGER,
    USER;

    public String getValue() {
        return name();
    }
}
